using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Pause : MonoBehaviour
{
    public static bool isPaused = false;
    public GameObject pauseMenuUI;

    
    // Start is called before the first frame update
    void Start()
    {
        pauseMenuUI.SetActive(false);
        Time.timeScale = 1f;
    }

    // Update is called once per frame
    void Update()
    {
        if(Input.GetKeyDown(KeyCode.Escape))
        {
            if(isPaused)
            {
                pauseMenuUI.SetActive(false);
                
                Time.timeScale = 1f;
                isPaused = false;
                Cursor.visible = false;
            }
            else
            {
                pauseMenuUI.SetActive(true);
                
                Time.timeScale =0f;
                isPaused = true;
                Cursor.visible = true;
            }

        }


    }
}
